### ISSUE TITLE
turn on AOT by default for development

### ISSUE THREAD

**Issue by robert-king** [maximegris/angular-tauri#3]
in angular.json dev configuration we could consider aot: true
since  in tsconfig we have  strictTemplates: true 
AFAIK AOT will force templates to be compiled during ng serve, and so strictTemplates will be checked.
 Otherwise we will only get a template compilation error during build AFAIK.
 
Bonus feature request:
consider using @Optional decorator for the tauri service. 
(https://medium.com/frontend-coach/self-or-optional-host-the-visual-guide-to-angular-di-decorators-73fbbb5c8658)
could be interesting since i'm planning to do most of my Dev from chrome outside the webview, so tauri isn't available. Otherwise I can use your method:

get isTauri(): boolean {
    return !!(window && window.__TAURI__);
  }

**Comment by maximegris** [comment]
@robert-king AOT is turned on for dev now.
